apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ip4-pv-volume
spec:
  storageClassName: my-ip4-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /mnt/my-ip4-pv-volume-data